### ISSUE TITLE
`read_cmd': uninitialized constant YleTf::System::StringIO (NameError)

### ISSUE THREAD

**Issue by PolarPayne** [Yleisradio/yle_tf#33]
Running yle_tf inside WSL2 Arch the following error happens.

```
Traceback (most recent call last):
        17: from /root/.gem/ruby/2.7.0/bin/tf:23:in `<main>'
        16: from /root/.gem/ruby/2.7.0/bin/tf:23:in `load'
        15: from /root/.gem/ruby/2.7.0/gems/yle_tf-1.2.0/bin/tf:11:in `<top (required)>'
        14: from /root/.gem/ruby/2.7.0/gems/yle_tf-1.2.0/lib/yle_tf/cli.rb:23:in `execute'
        13: from /root/.gem/ruby/2.7.0/gems/yle_tf-1.2.0/lib/yle_tf.rb:38:in `run'
        12: from /root/.gem/ruby/2.7.0/gems/yle_tf-1.2.0/vendor/middleware/builder.rb:112:in `call'
        11: from /root/.gem/ruby/2.7.0/gems/yle_tf-1.2.0/vendor/middleware/runner.rb:31:in `call'
        10: from /root/.gem/ruby/2.7.0/gems/yle_tf-1.2.0/lib/yle_tf/action/tmpdir.rb:21:in `call'
         9: from /root/.gem/ruby/2.7.0/gems/yle_tf-1.2.0/lib/yle_tf/action/tmpdir.rb:21:in `chdir'
         8: from /root/.gem/ruby/2.7.0/gems/yle_tf-1.2.0/lib/yle_tf/action/tmpdir.rb:22:in `block in call'
         7: from /root/.gem/ruby/2.7.0/gems/yle_tf-1.2.0/lib/yle_tf/action/command.rb:20:in `call'
         6: from /root/.gem/ruby/2.7.0/gems/yle_tf-1.2.0/lib/yle_tf_plugins/commands/help/command.rb:12:in `execute'
         5: from /root/.gem/ruby/2.7.0/gems/yle_tf-1.2.0/lib/yle_tf_plugins/commands/help/command.rb:18:in `opts'
         4: from /root/.gem/ruby/2.7.0/gems/yle_tf-1.2.0/lib/yle_tf_plugins/commands/help/command.rb:18:in `new'
         3: from /usr/lib/ruby/2.7.0/optparse.rb:1093:in `initialize'
         2: from /root/.gem/ruby/2.7.0/gems/yle_tf-1.2.0/lib/yle_tf_plugins/commands/help/command.rb:34:in `block in opts'
         1: from /root/.gem/ruby/2.7.0/gems/yle_tf-1.2.0/lib/yle_tf_plugins/commands/help/command.rb:60:in `terraform_help'
/root/.gem/ruby/2.7.0/gems/yle_tf-1.2.0/lib/yle_tf/system.rb:48:in `read_cmd': uninitialized constant YleTf::System::StringIO (NameError)
```

This can be fixed by adding `require 'stringio'` to [this file](https://github.com/Yleisradio/yle_tf/blob/master/lib/yle_tf_plugins/commands/help/command.rb). In addition to this, `thwait` gem needs to be separately installed for yle_tf to work.

**Comment by PolarPayne** [comment]
Ruby version: `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]`\
Gem version: `3.1.4`

**Comment by tmatilai** [comment]
This should be fixed in master by #30.

I'll try to cut a new release tonight.

**Comment by tmatilai** [comment]
Version 1.3.0 is out! Closing this but please confirm if all is good. 😊

**Comment by PolarPayne** [comment]
Yep, it's now working, thank you!
